webshop_backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['as' => 'index', 'uses' => 'backend\ChartController@index']);


Auth::routes();

//user Profile
Route::get('/profile', ['as' => 'profile', 'uses' => 'backend\ProfilesController@show']);
Route::post('/updateprofile', ['as' => 'updateprofile', 'uses' => 'backend\ProfilesController@updateprofile']);
Route::post('/updatepassword', ['as' => 'updatepassword', 'uses' => 'backend\ProfilesController@updatepassword']);

// orders
Route::resource('orders', 'backend\OrderController');
Route::get('/send_email', 'backend\EmailController@send_email')->name('send_email');

//resellers
// orders
Route::resource('resellers', 'backend\ResellerController');

//dodavanje popusta
Route::post('/setdiscount/{id}',['as' => 'setdiscount', 'uses' => 'backend\PopustController@setdiscount']);

//order_items
Route::resource('order_items', 'backend\OrderItemController');
// generate bills
Route::get('/export_excel', 'backend\OrderController@export_excel')->name('Export_excel');
Route::get('/export_word', 'backend\OrderController@export_word')->name('Export_word');
Route::get('/export_pdf/{id}', 'backend\OrderController@export_pdf')->name('Export_pdf');

// statistics
Route::resource('statistics', 'backend\StatisticController');

//charts home
Route::resource('charts','backend\ChartController');

webshop_backend/app/Http/Controllers/backend/ChartController.php
<?php

namespace App\Http\Controllers\backend;

use App\Mail\OrderConfirm;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\OrderItem;
use Mail;
use Session;
use PDF;

class ChartController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // grafik za narudzbine tekuce godine
        $orders_chart = \Lava::DataTable();
        $orders_chart->addStringColumn('Datum')
            ->addNumberColumn('Isporučeno')
            ->addNumberColumn('Odobreno')
            ->addNumberColumn('Na čekanju');
        $year = date('Y');
        for ( $i = 1;$i<13;$i++){
            $isporuceno= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('order_status',2)->count();
            $odobreno= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('order_status',1)->count();
            $naCekanju= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=',$i)->where('order_status',0)->count();
            $orders_chart->addRow([$i.'-'.$year,  $isporuceno, $odobreno, $naCekanju]);
        }

        \Lava::LineChart('OrdersChart', $orders_chart, [
            'title' => 'Pregled statusa narudžbina tekuće godine',
            'titleTextStyle' => [
                'color'    => '#eb6b2c',
                'fontSize' => 14
            ]
        ]);

        //grafik za zaradu u tekucoj godini
        $finances = \Lava::DataTable();

        $finances->addStringColumn('Mesec')
            ->addNumberColumn('Naplaćeno u rsd')
            ->addNumberColumn('Naručeno u rsd')
            ->setDateTimeFormat('M');
        for ( $i = 1;$i<13;$i++){
            $isporuceno= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('payment_status',2)->where('discounted_price', 0)->sum('total_price');
            $isporuceno_p= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('payment_status',2)->where('discounted_price','>', 0)->sum('discounted_price');
            $ukupno_isporuceno = $isporuceno + $isporuceno_p;
            $odobreno= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('payment_status',0)->where('discounted_price', 0)->sum('total_price');
            $odobreno_p= Order::whereYear('updated_at', '=', date('Y'))->whereMonth('updated_at', '=', $i)->where('payment_status',0)->where('discounted_price','>', 0)->sum('discounted_price');
            $ukupno_odobreno = $odobreno + $odobreno_p;
            $finances->addRow([$i.'-'.$year,  $ukupno_isporuceno, $ukupno_odobreno]);
        }

        \Lava::ColumnChart('Finances', $finances, [
            'title' => 'Pregled zarade tekuće godine',
            'titleTextStyle' => [
                'color'    => '#eb6b2c',
                'fontSize' => 14
            ]
        ]);


        return view('backend.chart');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



}

webshop_backend/app/Http/Controllers/backend/EmailController.php
<?php

namespace App\Http\Controllers\backend;

use App\Mail\NewOrder;
use App\Mail\OrderConfirm;
use App\Mail\OrderSaved;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\OrderItem;
use Mail;
use Session;
use PDF;

class EmailController extends Controller
{
    public function send_email(Request $request){
        $order_id =  $request->order_id;
        $order = Order::where('order_id',$order_id)->first();

        Mail::to($order->email)->send(new OrderSaved($order));
        Mail::to('perfect.socket@gmail.com')->send(new NewOrder($order));

        return 1;
    }
}

webshop_backend/app/Http/Controllers/backend/OrderController.php
<?php

namespace App\Http\Controllers\backend;

use App\Mail\OrderConfirm;
use App\Mail\OrderDelivery;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\OrderItem;
use Mail;
use Session;
use PDF;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::orderBy('id', 'desc')->get();
        return view('backend.orders')
            ->withOrders($orders);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        $orderItems = OrderItem::where('order_id', $id)->get();
        $i=1;
        return view('backend.order_details')
            ->withOrder($order)
            ->with('orderItems', $orderItems)->withI($i);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);
        $action = $request->action;
        $placanje = $request->placanje;
        if ($order->order_status == 0){
            Order::where('id', $id)->update(['order_status' => 1]);
            Session::flash('order_status_changed', 'Narudžbina (id - ' . $order->order_id .') je odobrena!');
            //priprema fakture i slanje emaila
            $this->export_pdf($order->id);
            Mail::to($order->email)->send(new OrderConfirm($order));
        }
        if ($order->order_status == 1){
            if($action == 0)
            {
                Order::where('id', $id)->update(['order_status' => 0]);
                Session::flash('order_status_changed', 'Narudžbini (id - ' . $order->order_id .') je ponisteno odobrenje!');
            }
            if($action == 2) {
                Order::where('id', $id)->update(['order_status' => 2]);
                Session::flash('order_status_changed', 'Narudžbina (id - ' . $order->order_id . ') je isporučena!');
            }
        }
        if ($order->order_status == 2){
            if($action == 1)
            {
                Order::where('id', $id)->update(['order_status' => 1]);
                Session::flash('order_status_changed', 'Narudžbini (id - ' . $order->order_id .') je ponistena isporuka!');
            }
        }
        //setovanje placanja
        if($placanje == 2)
        {
            Order::where('id', $id)->update(['payment_status' => 2]);
            Session::flash('order_status_changed', 'Narudžbina (id - ' . $order->order_id .') je placena!');
            Mail::to($order->email)->send(new OrderDelivery($order));
        }
        if($placanje == 0)
        {
            Order::where('id', $id)->update(['payment_status' => 0]);
            Session::flash('order_status_changed', 'Narudžbini (id - ' . $order->order_id .') je ponisteno placanje!');
        }
        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function export_excel(Request $request)
    {
        return Excel::load('templates/Bill.xls', function($excel) {
            $data = array(
                array('data1', 'data2'),
                array('data3', 'data4')
            );
            $excel->sheet('Sheet1', function ($sheet)use($data){
                //opis parametara metode ->fromArray($source, $nullValue, $startCell, $strictNullComparison, $headingGeneration)
                //https://laravel-excel.maatwebsite.nl/docs/2.1/export/array
                $sheet->fromArray($data, null, 'B2', false, false);
            });
        })->export('xls');
    }

    public function export_word(Request $request)
    {

        $template = new \PhpOffice\PhpWord\TemplateProcessor('../templates/Bill.docx');
        $test = "test_value";
        $template->setValue("test",$test);
        //ovo treba podesiti da se cuva u folderu za racune i da se u nazivu doda broj narudzbine
        $template->saveAs('../templates/Bill_test.docx');

        return response()->download("../templates/Bill_test.docx");
    }
    public function export_pdf($id)
    {
        $order = Order::find($id);
        $orderItems = OrderItem::where('order_id', $id)->get();
        $i=1;
        $pdf = PDF::loadView('backend.invoice', compact('order','orderItems','i'))->setPaper('a4', 'portrait');
        $pdf->save( 'invoices/Ponuda_broj_'.$order->order_id.'.pdf' );
        return $pdf->download('Ponuda_broj_'.$order->order_id.'.pdf');
    }
    public function send_email(Request $request){
        $order_id =  $request->order_id;
        return $order_id;
//        dd($order_id);
    }


}

webshop_backend/app/Http/Controllers/backend/PopustController.php
<?php

namespace App\Http\Controllers\backend;

use App\Mail\OrderConfirm;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\OrderItem;
use Mail;
use Session;
use PDF;
class PopustController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function setdiscount(Request $request, $id)
    {
            $order = Order::find($id);

            $discounted_price = $order->total_price * $request->popust;
            $discounted_price = number_format($discounted_price, 2, '.', '');
            Order::where('id', $id)->update(['discount' =>$request->popust , 'discounted_price' => $discounted_price]);
            Session::flash('order_status_changed', 'Popust je uspesno dodat!');


        return redirect()->route('orders.edit',$id);
    }
}

webshop_backend/app/Http/Controllers/backend/ProfilesController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use app\User;
use Hash;
use Session;

class ProfilesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    //show profile informations
    public function show(){
      return view('backend.profile');
    }

    //update informations
    public function updateprofile(Request $request){
      //validacija
      $this->validate($request, [
              'name' => 'required',
              'surname' => 'required',
              'telephone' => 'required',
              'email' => 'required',
              'address' => 'required',
              'floor' => 'required',
              'apartment_number' => 'required'
          ]);
      $user = User::find($request->id);
      $user->name = $request->name;
      $user->surname = $request->surname;
      $user->email = $request->email;
      $user->telephone = $request->telephone;
      $user->address = $request->address;
      $user->floor = $request->floor;
      $user->apartment_number = $request->apartment_number;
      $user->save();
      Session::flash('success_user', 'aжуриран профил корисника!');
    return redirect()->route('profile');
    }

    //update password
    public function updatepassword(Request $request){
      //validacija
      $this->validate($request, [
              'oldpassword' => 'required',
              'againpassword' => 'required',
              'newpassword' => 'required'
          ]);
      $user = User::find($request->id);

      if (Hash::check($request->oldpassword, $user->password))
      {
          if ($request->againpassword == $request->newpassword) {
            $user->password = bcrypt($request->newpassword);
            $user->save();
            Session::flash('success_password', ' ажурирана корисничка лозинка!');
            return redirect()->route('profile');
          }
      }else {
        Session::flash('error_password', 'Тренутна лозинка није валидна!');
        return redirect()->route('profile');
      }

    }
}

webshop_backend/resources/views/backend/create_reseller.blade.php
@extends('backend.main')
@section('content')
    <div class="page-content">
        <div class="row">
            @if (Session::has('success_password'))
                <div class="alert alert-success col-md-6 col-md-offset-3" role="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>Uspešno:</strong> {{ Session::get('success_password') }}
                </div>
            @endif
            @if (Session::has('success_user'))
                <div class="alert alert-success col-md-6 col-md-offset-3" role="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>Uspešno:</strong> {{ Session::get('success_user') }}
                </div>
            @endif
            @if (Session::has('error_password'))
                <div class="alert alert-danger col-md-6 col-md-offset-3" role="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>Greška: </strong> {{ Session::get('error_password') }}
                </div>
            @endif
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <div class="portlet light portlet-fit portlet-datatable bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-settings font-green"></i>
                            <span class="caption-subject font-green sbold uppercase"> Dodavanje novog preprodavca </span>
                        </div>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="tab-content">
                        <div class="tab-pane active col-md-4 col-md-offset-4 "  id="tab_1_1">
                            <form role="form" action="{{route('resellers.store')}}" method="post" data-parsley-validate>
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label class="control-label">Ime</label>
                                    <input type="text"  name="name" class="form-control" value="" required /> </div>
                                <div class="form-group">
                                    <label class="control-label">Prezime</label>
                                    <input type="text" name="surname" value="" class="form-control" required/> </div>
                                <div class="form-group">
                                    <label class="control-label">Email</label>
                                    <input type="text" name="email" value="" class="form-control" required /> </div>
                                <div class="form-group">
                                    <label class="control-label">Adresa</label>
                                    <input type="text" name="address" value="" class="form-control" required/> </div>
                                <div class="form-group">
                                    <label class="control-label">Stan</label>
                                    <input type="text" name="apartment" value="" class="form-control" /></div>
                                <div class="form-group">
                                    <label class="control-label">Grad</label>
                                    <input type="text" name="city" value="" class="form-control" required/></div>
                                <div class="form-group">
                                    <label class="control-label">Poštanski broj</label>
                                    <input type="text" name="post_number" value="" class="form-control" required/></div>
                                <div class="form-group">
                                    <label class="control-label">Telefon</label>
                                    <input type="text" name="telephone" value="" class="form-control" required  /> </div>
                                <div class="form-group">
                                    <label class="control-label">Popust</label>
                                    <select name="discount" id="discount" class="form-control">
                                        <option value="1">0 %</option>
                                        <option value="0.95">5 %</option>
                                        <option value="0.90">10 %</option>
                                        <option value="0.85">15 %</option>
                                        <option value="0.80">20 %</option>
                                    </select>
                                </div>


                                <div class="margiv-top-10">
                                    <button  type="submit" class="btn btn-success">
                                        <i class="fa fa-check"></i> Sačuvaj</button>
                                    <a href="{{ route('resellers.index') }}" class="btn default"> Nazad </a>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

webshop_backend/resources/views/backend/reseller_details.blade.php
@extends('backend.main')

@section('content')
    <div class="page-content">
        <div class="row">
            @if (Session::has('account_type_changed'))
                <div style="text-align: center" class="alert alert-success col-md-6 col-md-offset-3" role="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ Session::get('account_type_changed') }}</strong>
                </div>
            @endif
                @if (Session::has('reseller_changed'))
                    <div style="text-align: center" class="alert alert-success col-md-6 col-md-offset-3" role="alert">
                        <button type="button" class="close" data-dismiss="alert">x</button>
                        <strong>{{ Session::get('reseller_changed') }}</strong>
                    </div>
                @endif
                @if (Session::has('password_reset'))
                    <div style="text-align: center" class="alert alert-success col-md-6 col-md-offset-3" role="alert">
                        <button type="button" class="close" data-dismiss="alert">x</button>
                        <strong>{{ Session::get('password_reset') }}</strong>
                    </div>
                @endif

            {{--<div class="row">--}}
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <br>
                <div class="portlet light portlet-fit portlet-datatable bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-present font-green"></i>
                            <span class="caption-subject font-green sbold uppercase"> Prikaz podataka o preprodavcu </span>
                        </div>

                            @if($reseller->account_type == 'user')
                                <a style="float:right; margin-left: 5px;" href="{{ route('resellers.update', $reseller->id) }}"  class="btn btn-success"
                                   onclick="event.preventDefault();
                                   document.getElementById('account').value = 'reseller';
                                   document.getElementById('action').value = '-1';
                                    document.getElementById('update-form').submit();">
                                    <i class="glyphicon glyphicon-ok"></i>&nbsp;
                                    <span class="title">Potvrdi status preprodavca</span>
                                </a>
                            @else
                                <a style="float:right; margin-left: 5px;" href="{{ route('resellers.update', $reseller->id) }}"  class="btn btn-danger"
                                   onclick="event.preventDefault();
                                   document.getElementById('account').value = 'user';
                                   document.getElementById('action').value = '-1';
                                  document.getElementById('update-form').submit();">
                                    <i class="glyphicon glyphicon-remove"></i>&nbsp;
                                    <span class="title">Ponisti status preprodavca</span>
                                </a>
                            @endif
                        <a style="float:right; margin-left: 5px;" href="{{ route('resellers.destroy', $reseller->id) }}"  class="btn btn-danger"
                           onclick="event.preventDefault();
                                  document.getElementById('delete-form').submit();">
                            <i class="glyphicon glyphicon-remove"></i>&nbsp;
                            <span class="title">Obrisi preprodavca</span>
                        </a>

                        <form id="update-form" action="{{ route('resellers.update', $reseller->id) }}" method="POST" style="display: none;">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="account" id="account" value="-1">
                        </form>
                        <form id="delete-form" action="{{ route('resellers.destroy', $reseller->id) }}" method="POST" style="display: none;">
                            @csrf
                            @method('delete')
                        </form>

                    </div>
                    <div class="portlet-body">
                        <div class="tab-content">
                            <div class="tab-pane active col-md-4 col-md-offset-4 "  id="tab_1_1">
                                <form role="form" action="{{ route('resellers.update', $reseller->id) }}" method="post" data-parsley-validate>
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label class="control-label">Ime</label>
                                        <input type="text"  name="name" class="form-control" value="{{$reseller->name}}" required /> </div>
                                    <div class="form-group">
                                        <label class="control-label">Prezime</label>
                                        <input type="text" name="surname" value="{{$reseller->surname}}" class="form-control" required/> </div>
                                    <div class="form-group">
                                        <label class="control-label">Email</label>
                                        <input type="text" name="email" value="{{$reseller->email}}" class="form-control" required /> </div>
                                    <div class="form-group">
                                        <label class="control-label">Adresa</label>
                                        <input type="text" name="address" value="{{$reseller->address}}" class="form-control" required/> </div>
                                    <div class="form-group">
                                        <label class="control-label">Stan</label>
                                        <input type="text" name="apartment" value="{{$reseller->apartment}}" class="form-control" /></div>
                                    <div class="form-group">
                                        <label class="control-label">Grad</label>
                                        <input type="text" name="city" value="{{$reseller->city}}" class="form-control" required/></div>
                                    <div class="form-group">
                                        <label class="control-label">Postanski broj</label>
                                        <input type="text" name="post_number" value="{{$reseller->post_number}}" class="form-control" /></div>
                                    <div class="form-group">
                                        <label class="control-label">Telefon</label>
                                        <input type="text" name="telephone" value="{{$reseller->telephone}}" class="form-control" required  /> </div>
                                    <input type="hidden" name="account_type" value="{{$reseller->account_type}}" class="form-control" required  />
                                    @if($reseller->account_type == 'reseller')
                                    <div class="form-group">
                                        <label class="control-label">Popust</label>
                                        <select name="discount" id="discount" class="form-control">
                                            <option value="1" @if($reseller->discount == '1')  {{'selected'}}@endif>0 %</option>
                                            <option value="0.95" @if($reseller->discount == '0.95')  {{'selected'}}@endif>5 %</option>
                                            <option value="0.90" @if($reseller->discount == '0.90')  {{'selected'}}@endif>10 %</option>
                                            <option value="0.85" @if($reseller->discount == '0.85')  {{'selected'}}@endif>15 %</option>
                                            <option value="0.80" @if($reseller->discount == '0.80')  {{'selected'}}@endif>20 %</option>
                                        </select>
                                    </div>
                                    @endif
                                    <input type="hidden" name="action" id="action" value="update">

                                    <div class="margiv-top-10">
                                        <button  type="submit" class="btn btn-success">
                                            <i class="fa fa-check"></i> Sačuvaj</button>
                                        <a href="{{ route('resellers.edit',$reseller->id) }}" class="btn default"> Odustani </a>
                                    </div>

                                    <div class="margiv-top-10">
                                        <a href="{{ route('resellers.show',$reseller->id) }}" class="btn btn-primary form-control" style="margin-top: 5px;"> Resetovanje lozinke </a>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
<script>
    function showDiscount() {
        document.getElementById('dugmePopust').style.display="none";
        document.getElementById('izborPopusta').style.display= "block";
    }

    function dodajPopust() {
        var popust = document.getElementById('popust').value;
        $('$iznos_popusta').val(popust);
        alert(document.getElementById('iznos_popusta').value);

    }


</script>